### ISSUE TITLE
State/Province dropdown not populated

### ISSUE THREAD

**Issue by richardjkeys** [PCAPredict/magento2#4]
When selecting a US address, the State/Province field doesn't get selected as expected.

Support have said my dropdown is customised, but we've not edited the way the form works. Options in the form look as follows:

`<option value="1">Alabama</option>`

Support suggested I'd need to edit these options somehow, but that seems unnecessary.

**Comment by rikhowarth** [comment]
Hi, thanks for highlighting this problem! 
To address this issue, we will be pushing out a new version today. I'll update and close this issue when the new version (1.0.7) is uploaded here.

**Comment by rikhowarth** [comment]
This issue should now be fixed with version 1.0.7
The custom mappings in the settings screen should also be updated to the contents of the below file. If you have modified mappings, or need help changing the mappings, please contact support for assistance.

[magento2-default-mappings_107.zip](https://github.com/PCAPredict/magento2/files/474682/magento2-default-mappings_107.zip)

**Comment by richardjkeys** [comment]
Works a treat! Thanks so much :)
